version: 2.1

executors:
  builder:
    docker:
      - image: telus/build-essential

  browsers:
    docker:
      - image: circleci/node:8-browsers

  prepr:
    docker:
      - image: circleci/node:8

commands:
  persist:
    steps:
      - persist_to_workspace:
          root: .
          paths: .

  attach:
    steps:
      - attach_workspace:
          at: .

  expect:
    steps:
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y expect

  install:
    steps:
      - run:
          name: Install dependencies
          command: npm ci

jobs:
  build:
    executor: builder
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: npm run bootstrap
      - persist

  lint:
    executor: builder
    steps:
      - attach
      - run: npm run lint

  unit:
    executor: builder
    steps:
      - attach
      - run: npm run test

  prepr-log:
    executor: prepr
    steps:
      - attach
      - expect
      - run:
          name: Package version bumps
          command: scripts/prePr.sh

  release:
    executor: builder
    steps:
      - attach
      - add_ssh_keys:
          fingerprints:
            - 'd8:9c:6b:f9:de:c6:98:8e:07:43:7a:9c:51:7a:69:7d'
      - run:
          name: Add Github Key
          command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run:
          name: Configure Git Config & Branch
          command: |
            git status
            git config --global user.email "szhang@nascentdigital.com"
            git config --global user.name "Sonny Zhang"
            git fetch origin --tags
      - run:
          name: Setup .npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Lerna Publish
          command: npm run lerna:cipublish

workflows:
  version: 2
  run:
    jobs:
      - build

      - lint:
          requires: [build]

      - unit:
          requires: [build]

      - prepr-log:
          requires: [build, lint, unit]
          filters:
            branches:
              only: master

      - approve-release:
          type: approval
          requires: [build, lint, unit, prepr-log]
          filters:
            branches:
              only: master

      - release:
          context: npm-library
          requires: [approve-release]
